name: Deploy Spring Boot to EC2

on:
  push:
    branches:
      - main  # Runs on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH and deploy
        run: |
          # Create the PEM file from GitHub secret
          echo "${{ secrets.EC2_PEM_KEY }}" > ec2-key.pem
          chmod 400 ec2-key.pem

          # SSH into the EC2 instance and deploy the application
          ssh -o StrictHostKeyChecking=no -i ec2-key.pem ec2-user@13.60.229.72 << 'EOF'
            # Navigate to your app folder
            cd /home/ec2-user/springbootapp

            # Pull the latest changes from GitHub
            git pull origin main

            # Build the project using Maven (or Gradle)
            ./mvnw clean package

            # Stop the old Spring Boot app
            pkill -f 'java -jar' || true

            # Run the new JAR
            nohup java -jar target/your-spring-boot-app.jar > app.log 2>&1 &

            # Exit the SSH session
            exit
          EOF
